## static_countries
UPDATE static_countries SET cn_short_ko='안도라',cn_iso_2='AD' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_ko='아랍에미리트 연합',cn_iso_2='AE' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_ko='아프가니스탄',cn_iso_2='AF' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_ko='앤티가 바부다',cn_iso_2='AG' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_ko='안길라',cn_iso_2='AI' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_ko='알바니아',cn_iso_2='AL' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_ko='아르메니아',cn_iso_2='AM' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_ko='앙골라',cn_iso_2='AO' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_ko='남극 대륙',cn_iso_2='AQ' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_ko='아르헨티나',cn_iso_2='AR' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_ko='아메리칸 사모아',cn_iso_2='AS' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_ko='오스트리아',cn_iso_2='AT' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_ko='오스트레일리아',cn_iso_2='AU' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_ko='아루바',cn_iso_2='AW' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_ko='아제르바이잔',cn_iso_2='AZ' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_ko='보스니아 헤르체고비나',cn_iso_2='BA' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_ko='바베이도스',cn_iso_2='BB' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_ko='방글라데시',cn_iso_2='BD' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_ko='벨기에',cn_iso_2='BE' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_ko='부르키나파소',cn_iso_2='BF' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_ko='불가리아',cn_iso_2='BG' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_ko='바레인',cn_iso_2='BH' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_ko='부룬디',cn_iso_2='BI' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_ko='베냉',cn_iso_2='BJ' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_ko='버뮤다',cn_iso_2='BM' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_ko='브루나이',cn_iso_2='BN' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_ko='볼리비아',cn_iso_2='BO' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_ko='브라질',cn_iso_2='BR' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_ko='바하마',cn_iso_2='BS' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_ko='부탄',cn_iso_2='BT' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_ko='부베',cn_iso_2='BV' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_ko='보츠와나',cn_iso_2='BW' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_ko='벨라루스',cn_iso_2='BY' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_ko='벨리즈',cn_iso_2='BZ' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_ko='캐나다',cn_iso_2='CA' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_ko='코코스제도',cn_iso_2='CC' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_ko='콩고민주공화국',cn_iso_2='CD' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_ko='중앙 아프리카 공화국',cn_iso_2='CF' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_ko='콩고 공화국',cn_iso_2='CG' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_ko='스위스',cn_iso_2='CH' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_ko='코트디부아르',cn_iso_2='CI' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_ko='쿡제도',cn_iso_2='CK' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_ko='칠레',cn_iso_2='CL' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_ko='카메룬',cn_iso_2='CM' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_ko='중국',cn_iso_2='CN' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_ko='콜롬비아',cn_iso_2='CO' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_ko='코스타리카',cn_iso_2='CR' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_ko='쿠바',cn_iso_2='CU' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_ko='까뽀베르데',cn_iso_2='CV' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_ko='크리스마스섬',cn_iso_2='CX' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_ko='사이프러스',cn_iso_2='CY' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_ko='체코',cn_iso_2='CZ' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_ko='독일',cn_iso_2='DE' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_ko='지부티',cn_iso_2='DJ' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_ko='덴마크',cn_iso_2='DK' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_ko='도미니카',cn_iso_2='DM' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_ko='도미니카 공화국',cn_iso_2='DO' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_ko='알제리',cn_iso_2='DZ' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_ko='에콰도르',cn_iso_2='EC' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_ko='에스토니아',cn_iso_2='EE' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_ko='이집트',cn_iso_2='EG' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_ko='서사하라',cn_iso_2='EH' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_ko='에리트리아',cn_iso_2='ER' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_ko='스페인',cn_iso_2='ES' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_ko='이디오피아',cn_iso_2='ET' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_ko='핀란드',cn_iso_2='FI' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_ko='피지',cn_iso_2='FJ' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_ko='포클랜드 제도(말비나스 군도)',cn_iso_2='FK' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_ko='미크로네시아',cn_iso_2='FM' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_ko='페로제도',cn_iso_2='FO' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_ko='프랑스',cn_iso_2='FR' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_ko='가봉',cn_iso_2='GA' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_ko='영국',cn_iso_2='GB' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_ko='그레나다',cn_iso_2='GD' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_ko='조지아',cn_iso_2='GE' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_ko='프랑스령 기아나',cn_iso_2='GF' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_ko='가나',cn_iso_2='GH' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_ko='지브롤터',cn_iso_2='GI' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_ko='그린란드',cn_iso_2='GL' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_ko='감비아',cn_iso_2='GM' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_ko='기니',cn_iso_2='GN' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_ko='과들루프',cn_iso_2='GP' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_ko='적도 기니',cn_iso_2='GQ' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_ko='그리스',cn_iso_2='GR' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_ko='사우스조지아 사우스샌드위치 제도',cn_iso_2='GS' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_ko='과테말라',cn_iso_2='GT' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_ko='괌',cn_iso_2='GU' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_ko='기네비쏘',cn_iso_2='GW' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_ko='가이아나',cn_iso_2='GY' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_ko='홍콩',cn_iso_2='HK' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_ko='온두라스',cn_iso_2='HN' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_ko='크로아티아',cn_iso_2='HR' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_ko='아이티',cn_iso_2='HT' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_ko='헝가리',cn_iso_2='HU' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_ko='인도네시아',cn_iso_2='ID' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_ko='아일랜드',cn_iso_2='IE' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_ko='이스라엘',cn_iso_2='IL' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_ko='인도',cn_iso_2='IN' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_ko='영국령인도양식민지',cn_iso_2='IO' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_ko='이라크',cn_iso_2='IQ' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_ko='이란',cn_iso_2='IR' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_ko='아이슬란드',cn_iso_2='IS' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_ko='이탈리아',cn_iso_2='IT' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_ko='자메이카',cn_iso_2='JM' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_ko='요르단',cn_iso_2='JO' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_ko='일본',cn_iso_2='JP' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_ko='케냐',cn_iso_2='KE' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_ko='키르기스스탄',cn_iso_2='KG' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_ko='캄보디아',cn_iso_2='KH' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_ko='키리바시',cn_iso_2='KI' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_ko='코모로스',cn_iso_2='KM' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_ko='세인트크리스토퍼 네비스',cn_iso_2='KN' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_ko='조선 민주주의 인민 공화국',cn_iso_2='KP' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_ko='대한민국',cn_iso_2='KR' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_ko='쿠웨이트',cn_iso_2='KW' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_ko='케이맨제도',cn_iso_2='KY' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_ko='카자흐스탄',cn_iso_2='KZ' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_ko='라오스',cn_iso_2='LA' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_ko='레바논',cn_iso_2='LB' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_ko='세인트루시아',cn_iso_2='LC' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_ko='리히텐슈타인',cn_iso_2='LI' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_ko='스리랑카',cn_iso_2='LK' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_ko='라이베리아',cn_iso_2='LR' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_ko='레소토',cn_iso_2='LS' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_ko='리투아니아',cn_iso_2='LT' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_ko='룩셈부르크',cn_iso_2='LU' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_ko='라트비아',cn_iso_2='LV' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_ko='리비아',cn_iso_2='LY' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_ko='모로코',cn_iso_2='MA' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_ko='모나코',cn_iso_2='MC' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_ko='몰도바',cn_iso_2='MD' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_ko='마다가스카르',cn_iso_2='MG' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_ko='마샬 군도',cn_iso_2='MH' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_ko='마케도니아(FYROM)',cn_iso_2='MK' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_ko='말리',cn_iso_2='ML' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_ko='미얀마',cn_iso_2='MM' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_ko='몽골',cn_iso_2='MN' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_ko='마카오',cn_iso_2='MO' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_ko='북마리아나제도',cn_iso_2='MP' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_ko='말티니크',cn_iso_2='MQ' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_ko='모리타니',cn_iso_2='MR' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_ko='몬트세라트',cn_iso_2='MS' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_ko='몰타',cn_iso_2='MT' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_ko='모리셔스',cn_iso_2='MU' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_ko='몰디브',cn_iso_2='MV' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_ko='말라위',cn_iso_2='MW' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_ko='멕시코',cn_iso_2='MX' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_ko='말레이시아',cn_iso_2='MY' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_ko='모잠비크',cn_iso_2='MZ' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_ko='나미비아',cn_iso_2='NA' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_ko='뉴 칼레도니아',cn_iso_2='NC' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_ko='니제르',cn_iso_2='NE' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_ko='노퍽섬',cn_iso_2='NF' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_ko='나이지리아',cn_iso_2='NG' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_ko='니카라과',cn_iso_2='NI' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_ko='네덜란드',cn_iso_2='NL' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_ko='노르웨이',cn_iso_2='NO' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_ko='네팔',cn_iso_2='NP' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_ko='나우루',cn_iso_2='NR' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_ko='니우에',cn_iso_2='NU' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_ko='뉴질랜드',cn_iso_2='NZ' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_ko='오만',cn_iso_2='OM' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_ko='파나마',cn_iso_2='PA' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_ko='페루',cn_iso_2='PE' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_ko='프랑스령 폴리네시아',cn_iso_2='PF' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_ko='파푸아뉴기니',cn_iso_2='PG' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_ko='필리핀',cn_iso_2='PH' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_ko='파키스탄',cn_iso_2='PK' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_ko='폴란드',cn_iso_2='PL' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_ko='세인트피에르-미케롱',cn_iso_2='PM' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_ko='핏케언섬',cn_iso_2='PN' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_ko='푸에르토리코',cn_iso_2='PR' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_ko='포르투갈',cn_iso_2='PT' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_ko='팔라우',cn_iso_2='PW' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_ko='파라과이',cn_iso_2='PY' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_ko='카타르',cn_iso_2='QA' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_ko='리유니온',cn_iso_2='RE' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_ko='루마니아',cn_iso_2='RO' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_ko='러시아',cn_iso_2='RU' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_ko='르완다',cn_iso_2='RW' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_ko='사우디아라비아',cn_iso_2='SA' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_ko='솔로몬 제도',cn_iso_2='SB' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_ko='쉐이쉘',cn_iso_2='SC' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_ko='수단',cn_iso_2='SD' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_ko='스웨덴',cn_iso_2='SE' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_ko='싱가포르',cn_iso_2='SG' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_ko='세인트헬레나',cn_iso_2='SH' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_ko='슬로베니아',cn_iso_2='SI' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_ko='스발바르제도-얀마웬섬',cn_iso_2='SJ' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_ko='슬로바키아',cn_iso_2='SK' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_ko='시에라리온',cn_iso_2='SL' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_ko='산마리노',cn_iso_2='SM' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_ko='세네갈',cn_iso_2='SN' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_ko='소말리아',cn_iso_2='SO' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_ko='수리남',cn_iso_2='SR' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_ko='상투메 프린시페',cn_iso_2='ST' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_ko='엘살바도르',cn_iso_2='SV' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_ko='시리아',cn_iso_2='SY' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_ko='스와질랜드',cn_iso_2='SZ' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_ko='터크스케이커스제도',cn_iso_2='TC' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_ko='차드',cn_iso_2='TD' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_ko='프랑스 남부 지방',cn_iso_2='TF' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_ko='토고',cn_iso_2='TG' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_ko='태국',cn_iso_2='TH' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_ko='타지키스탄',cn_iso_2='TJ' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_ko='토켈라우',cn_iso_2='TK' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_ko='투르크메니스탄',cn_iso_2='TM' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_ko='튀니지',cn_iso_2='TN' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_ko='통가',cn_iso_2='TO' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_ko='동티모르',cn_iso_2='TL' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_ko='터키',cn_iso_2='TR' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_ko='트리니다드 토바고',cn_iso_2='TT' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_ko='투발루',cn_iso_2='TV' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_ko='대만',cn_iso_2='TW' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_ko='탄자니아',cn_iso_2='TZ' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_ko='우크라이나',cn_iso_2='UA' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_ko='우간다',cn_iso_2='UG' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_ko='미국령 해외 제도',cn_iso_2='UM' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_ko='미국',cn_iso_2='US' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_ko='우루과이',cn_iso_2='UY' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_ko='우즈베키스탄',cn_iso_2='UZ' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_ko='바티칸',cn_iso_2='VA' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_ko='세인트빈센트그레나딘',cn_iso_2='VC' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_ko='베네수엘라',cn_iso_2='VE' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_ko='영국령 버진 아일랜드',cn_iso_2='VG' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_ko='미국령 버진 아일랜드',cn_iso_2='VI' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_ko='베트남',cn_iso_2='VN' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_ko='바누아투',cn_iso_2='VU' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_ko='왈리스-푸투나 제도',cn_iso_2='WF' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_ko='사모아',cn_iso_2='WS' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_ko='예멘',cn_iso_2='YE' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_ko='마요티',cn_iso_2='YT' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_ko='남아프리카',cn_iso_2='ZA' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_ko='잠비아',cn_iso_2='ZM' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_ko='짐바브웨',cn_iso_2='ZW' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_ko='팔레스타인',cn_iso_2='PS' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_ko='올란드 제도',cn_iso_2='AX' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_ko='허드섬-맥도널드제도',cn_iso_2='HM' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_ko='몬테네그로',cn_iso_2='ME' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_ko='세르비아',cn_iso_2='RS' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_ko='저지',cn_iso_2='JE' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_ko='건지',cn_iso_2='GG' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_ko='맨 섬',cn_iso_2='IM' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_ko='생 마르탱',cn_iso_2='MF' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_ko='생 바르텔르미',cn_iso_2='BL' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_ko='네덜란드령 카리브',cn_iso_2='BQ' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_ko='퀴라소',cn_iso_2='CW' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_ko='신트마르턴',cn_iso_2='SX' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_ko='남수단',cn_iso_2='SS' WHERE cn_iso_2='SS';
UPDATE static_countries SET cn_short_ko='어센션 섬',cn_iso_2='AC' WHERE cn_iso_2='AC';
UPDATE static_countries SET cn_short_ko='네덜란드령 안틸레스',cn_iso_2='AN' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_ko='클립퍼튼 섬',cn_iso_2='CP' WHERE cn_iso_2='CP';
UPDATE static_countries SET cn_short_ko='디에고 가르시아',cn_iso_2='DG' WHERE cn_iso_2='DG';
UPDATE static_countries SET cn_short_ko='세우타 및 멜리야',cn_iso_2='EA' WHERE cn_iso_2='EA';
UPDATE static_countries SET cn_short_ko='유럽 연합',cn_iso_2='EU' WHERE cn_iso_2='EU';
UPDATE static_countries SET cn_short_ko='카나리아 제도',cn_iso_2='IC' WHERE cn_iso_2='IC';
UPDATE static_countries SET cn_short_ko='오세아니아 외곽',cn_iso_2='QO' WHERE cn_iso_2='QO';
UPDATE static_countries SET cn_short_ko='트리스탄다쿠나',cn_iso_2='TA' WHERE cn_iso_2='TA';
UPDATE static_countries SET cn_short_ko='코소보',cn_iso_2='XK' WHERE cn_iso_2='XK';
UPDATE static_countries SET cn_short_ko='알수없거나 유효하지 않은 지역',cn_iso_2='ZZ' WHERE cn_iso_2='ZZ';

## static_languages
UPDATE static_languages SET lg_name_ko='압카즈어',lg_iso_2='AB' WHERE lg_iso_2='AB';
UPDATE static_languages SET lg_name_ko='아파르어',lg_iso_2='AA' WHERE lg_iso_2='AA';
UPDATE static_languages SET lg_name_ko='남아공 공용어',lg_iso_2='AF' WHERE lg_iso_2='AF';
UPDATE static_languages SET lg_name_ko='알바니아어',lg_iso_2='SQ' WHERE lg_iso_2='SQ';
UPDATE static_languages SET lg_name_ko='암하라어',lg_iso_2='AM' WHERE lg_iso_2='AM';
UPDATE static_languages SET lg_name_ko='아랍어',lg_iso_2='AR' WHERE lg_iso_2='AR';
UPDATE static_languages SET lg_name_ko='아르메니아어',lg_iso_2='HY' WHERE lg_iso_2='HY';
UPDATE static_languages SET lg_name_ko='아샘어',lg_iso_2='AS' WHERE lg_iso_2='AS';
UPDATE static_languages SET lg_name_ko='아이마라어',lg_iso_2='AY' WHERE lg_iso_2='AY';
UPDATE static_languages SET lg_name_ko='아제리어',lg_iso_2='AZ' WHERE lg_iso_2='AZ';
UPDATE static_languages SET lg_name_ko='바슈키르어',lg_iso_2='BA' WHERE lg_iso_2='BA';
UPDATE static_languages SET lg_name_ko='바스크어',lg_iso_2='EU' WHERE lg_iso_2='EU';
UPDATE static_languages SET lg_name_ko='벵골어',lg_iso_2='BN' WHERE lg_iso_2='BN';
UPDATE static_languages SET lg_name_ko='종카어',lg_iso_2='DZ' WHERE lg_iso_2='DZ';
UPDATE static_languages SET lg_name_ko='비하르어',lg_iso_2='BH' WHERE lg_iso_2='BH';
UPDATE static_languages SET lg_name_ko='비슬라마어',lg_iso_2='BI' WHERE lg_iso_2='BI';
UPDATE static_languages SET lg_name_ko='브르타뉴어',lg_iso_2='BR' WHERE lg_iso_2='BR';
UPDATE static_languages SET lg_name_ko='불가리아어',lg_iso_2='BG' WHERE lg_iso_2='BG';
UPDATE static_languages SET lg_name_ko='버마어',lg_iso_2='MY' WHERE lg_iso_2='MY';
UPDATE static_languages SET lg_name_ko='벨라루스어',lg_iso_2='BE' WHERE lg_iso_2='BE';
UPDATE static_languages SET lg_name_ko='캄보디아어',lg_iso_2='KM' WHERE lg_iso_2='KM';
UPDATE static_languages SET lg_name_ko='카탈로니아어',lg_iso_2='CA' WHERE lg_iso_2='CA';
UPDATE static_languages SET lg_name_ko='주앙어',lg_iso_2='ZA' WHERE lg_iso_2='ZA';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='코르시카어',lg_iso_2='CO' WHERE lg_iso_2='CO';
UPDATE static_languages SET lg_name_ko='크로아티아어',lg_iso_2='HR' WHERE lg_iso_2='HR';
UPDATE static_languages SET lg_name_ko='체코어',lg_iso_2='CS' WHERE lg_iso_2='CS';
UPDATE static_languages SET lg_name_ko='덴마크어',lg_iso_2='DA' WHERE lg_iso_2='DA';
UPDATE static_languages SET lg_name_ko='네덜란드어',lg_iso_2='NL' WHERE lg_iso_2='NL';
UPDATE static_languages SET lg_name_ko='영어',lg_iso_2='EN' WHERE lg_iso_2='EN';
UPDATE static_languages SET lg_name_ko='에스페란토어',lg_iso_2='EO' WHERE lg_iso_2='EO';
UPDATE static_languages SET lg_name_ko='에스토니아어',lg_iso_2='ET' WHERE lg_iso_2='ET';
UPDATE static_languages SET lg_name_ko='페로어',lg_iso_2='FO' WHERE lg_iso_2='FO';
UPDATE static_languages SET lg_name_ko='페르시아어',lg_iso_2='FA' WHERE lg_iso_2='FA';
UPDATE static_languages SET lg_name_ko='피지어',lg_iso_2='FJ' WHERE lg_iso_2='FJ';
UPDATE static_languages SET lg_name_ko='핀란드어',lg_iso_2='FI' WHERE lg_iso_2='FI';
UPDATE static_languages SET lg_name_ko='프랑스어',lg_iso_2='FR' WHERE lg_iso_2='FR';
UPDATE static_languages SET lg_name_ko='프리지아어',lg_iso_2='FY' WHERE lg_iso_2='FY';
UPDATE static_languages SET lg_name_ko='갈리시아어',lg_iso_2='GL' WHERE lg_iso_2='GL';
UPDATE static_languages SET lg_name_ko='스코틀랜드 게일어',lg_iso_2='GD' WHERE lg_iso_2='GD';
UPDATE static_languages SET lg_name_ko='맹크스어',lg_iso_2='GV' WHERE lg_iso_2='GV';
UPDATE static_languages SET lg_name_ko='조지아어',lg_iso_2='KA' WHERE lg_iso_2='KA';
UPDATE static_languages SET lg_name_ko='독일어',lg_iso_2='DE' WHERE lg_iso_2='DE';
UPDATE static_languages SET lg_name_ko='그리스어',lg_iso_2='EL' WHERE lg_iso_2='EL';
UPDATE static_languages SET lg_name_ko='그린란드어',lg_iso_2='KL' WHERE lg_iso_2='KL';
UPDATE static_languages SET lg_name_ko='과라니어',lg_iso_2='GN' WHERE lg_iso_2='GN';
UPDATE static_languages SET lg_name_ko='구자라트어',lg_iso_2='GU' WHERE lg_iso_2='GU';
UPDATE static_languages SET lg_name_ko='하우사어',lg_iso_2='HA' WHERE lg_iso_2='HA';
UPDATE static_languages SET lg_name_ko='히브리어',lg_iso_2='HE' WHERE lg_iso_2='HE';
UPDATE static_languages SET lg_name_ko='힌디어',lg_iso_2='HI' WHERE lg_iso_2='HI';
UPDATE static_languages SET lg_name_ko='헝가리어',lg_iso_2='HU' WHERE lg_iso_2='HU';
UPDATE static_languages SET lg_name_ko='아이슬란드어',lg_iso_2='IS' WHERE lg_iso_2='IS';
UPDATE static_languages SET lg_name_ko='인도네시아어',lg_iso_2='ID' WHERE lg_iso_2='ID';
UPDATE static_languages SET lg_name_ko='인테르링구아 (국제보조어협회)',lg_iso_2='IA' WHERE lg_iso_2='IA';
UPDATE static_languages SET lg_name_ko='인테르링구에',lg_iso_2='IE' WHERE lg_iso_2='IE';
UPDATE static_languages SET lg_name_ko='이눅티투트어',lg_iso_2='IU' WHERE lg_iso_2='IU';
UPDATE static_languages SET lg_name_ko='이누피아크어',lg_iso_2='IK' WHERE lg_iso_2='IK';
UPDATE static_languages SET lg_name_ko='아일랜드어',lg_iso_2='GA' WHERE lg_iso_2='GA';
UPDATE static_languages SET lg_name_ko='이탈리아어',lg_iso_2='IT' WHERE lg_iso_2='IT';
UPDATE static_languages SET lg_name_ko='일본어',lg_iso_2='JA' WHERE lg_iso_2='JA';
UPDATE static_languages SET lg_name_ko='칸나다어',lg_iso_2='KN' WHERE lg_iso_2='KN';
UPDATE static_languages SET lg_name_ko='카슈미르어',lg_iso_2='KS' WHERE lg_iso_2='KS';
UPDATE static_languages SET lg_name_ko='카자흐어',lg_iso_2='KK' WHERE lg_iso_2='KK';
UPDATE static_languages SET lg_name_ko='르완다어',lg_iso_2='RW' WHERE lg_iso_2='RW';
UPDATE static_languages SET lg_name_ko='키르기스어',lg_iso_2='KY' WHERE lg_iso_2='KY';
UPDATE static_languages SET lg_name_ko='룬디어',lg_iso_2='RN' WHERE lg_iso_2='RN';
UPDATE static_languages SET lg_name_ko='한국어',lg_iso_2='KO' WHERE lg_iso_2='KO';
UPDATE static_languages SET lg_name_ko='쿠르드어',lg_iso_2='KU' WHERE lg_iso_2='KU';
UPDATE static_languages SET lg_name_ko='라오어',lg_iso_2='LO' WHERE lg_iso_2='LO';
UPDATE static_languages SET lg_name_ko='라틴어',lg_iso_2='LA' WHERE lg_iso_2='LA';
UPDATE static_languages SET lg_name_ko='라트비아어',lg_iso_2='LV' WHERE lg_iso_2='LV';
UPDATE static_languages SET lg_name_ko='링갈라어',lg_iso_2='LN' WHERE lg_iso_2='LN';
UPDATE static_languages SET lg_name_ko='리투아니아어',lg_iso_2='LT' WHERE lg_iso_2='LT';
UPDATE static_languages SET lg_name_ko='마케도니아어',lg_iso_2='MK' WHERE lg_iso_2='MK';
UPDATE static_languages SET lg_name_ko='말라가시어',lg_iso_2='MG' WHERE lg_iso_2='MG';
UPDATE static_languages SET lg_name_ko='말레이어',lg_iso_2='MS' WHERE lg_iso_2='MS';
UPDATE static_languages SET lg_name_ko='말라얄람어',lg_iso_2='ML' WHERE lg_iso_2='ML';
UPDATE static_languages SET lg_name_ko='몰타어',lg_iso_2='MT' WHERE lg_iso_2='MT';
UPDATE static_languages SET lg_name_ko='마오리어',lg_iso_2='MI' WHERE lg_iso_2='MI';
UPDATE static_languages SET lg_name_ko='마라티어',lg_iso_2='MR' WHERE lg_iso_2='MR';
UPDATE static_languages SET lg_name_ko='몰도바어',lg_iso_2='MO' WHERE lg_iso_2='MO';
UPDATE static_languages SET lg_name_ko='몽고어',lg_iso_2='MN' WHERE lg_iso_2='MN';
UPDATE static_languages SET lg_name_ko='나우루어',lg_iso_2='NA' WHERE lg_iso_2='NA';
UPDATE static_languages SET lg_name_ko='네팔어',lg_iso_2='NE' WHERE lg_iso_2='NE';
UPDATE static_languages SET lg_name_ko='노르웨이어',lg_iso_2='NO' WHERE lg_iso_2='NO';
UPDATE static_languages SET lg_name_ko='오크어',lg_iso_2='OC' WHERE lg_iso_2='OC';
UPDATE static_languages SET lg_name_ko='오리야어',lg_iso_2='OR' WHERE lg_iso_2='OR';
UPDATE static_languages SET lg_name_ko='오로모어',lg_iso_2='OM' WHERE lg_iso_2='OM';
UPDATE static_languages SET lg_name_ko='파슈토어',lg_iso_2='PS' WHERE lg_iso_2='PS';
UPDATE static_languages SET lg_name_ko='폴란드어',lg_iso_2='PL' WHERE lg_iso_2='PL';
UPDATE static_languages SET lg_name_ko='포르투갈어',lg_iso_2='PT' WHERE lg_iso_2='PT';
UPDATE static_languages SET lg_name_ko='펀잡어',lg_iso_2='PA' WHERE lg_iso_2='PA';
UPDATE static_languages SET lg_name_ko='케추아어',lg_iso_2='QU' WHERE lg_iso_2='QU';
UPDATE static_languages SET lg_name_ko='레토로만어',lg_iso_2='RM' WHERE lg_iso_2='RM';
UPDATE static_languages SET lg_name_ko='루마니아어',lg_iso_2='RO' WHERE lg_iso_2='RO';
UPDATE static_languages SET lg_name_ko='러시아어',lg_iso_2='RU' WHERE lg_iso_2='RU';
UPDATE static_languages SET lg_name_ko='사모아어',lg_iso_2='SM' WHERE lg_iso_2='SM';
UPDATE static_languages SET lg_name_ko='산고어',lg_iso_2='SG' WHERE lg_iso_2='SG';
UPDATE static_languages SET lg_name_ko='산스크리트어',lg_iso_2='SA' WHERE lg_iso_2='SA';
UPDATE static_languages SET lg_name_ko='세르비아어',lg_iso_2='SR' WHERE lg_iso_2='SR';
UPDATE static_languages SET lg_name_ko='소토어 (남부)',lg_iso_2='ST' WHERE lg_iso_2='ST';
UPDATE static_languages SET lg_name_ko='세츠와나어',lg_iso_2='TN' WHERE lg_iso_2='TN';
UPDATE static_languages SET lg_name_ko='쇼나어',lg_iso_2='SN' WHERE lg_iso_2='SN';
UPDATE static_languages SET lg_name_ko='신디어',lg_iso_2='SD' WHERE lg_iso_2='SD';
UPDATE static_languages SET lg_name_ko='스리랑카어',lg_iso_2='SI' WHERE lg_iso_2='SI';
UPDATE static_languages SET lg_name_ko='시스와티어',lg_iso_2='SS' WHERE lg_iso_2='SS';
UPDATE static_languages SET lg_name_ko='슬로바키아어',lg_iso_2='SK' WHERE lg_iso_2='SK';
UPDATE static_languages SET lg_name_ko='슬로베니아어',lg_iso_2='SL' WHERE lg_iso_2='SL';
UPDATE static_languages SET lg_name_ko='소말리아어',lg_iso_2='SO' WHERE lg_iso_2='SO';
UPDATE static_languages SET lg_name_ko='스페인어',lg_iso_2='ES' WHERE lg_iso_2='ES';
UPDATE static_languages SET lg_name_ko='순다어',lg_iso_2='SU' WHERE lg_iso_2='SU';
UPDATE static_languages SET lg_name_ko='스와힐리어',lg_iso_2='SW' WHERE lg_iso_2='SW';
UPDATE static_languages SET lg_name_ko='스웨덴어',lg_iso_2='SV' WHERE lg_iso_2='SV';
UPDATE static_languages SET lg_name_ko='타갈로그어',lg_iso_2='TL' WHERE lg_iso_2='TL';
UPDATE static_languages SET lg_name_ko='타지키스탄어',lg_iso_2='TG' WHERE lg_iso_2='TG';
UPDATE static_languages SET lg_name_ko='타밀어',lg_iso_2='TA' WHERE lg_iso_2='TA';
UPDATE static_languages SET lg_name_ko='타타르어',lg_iso_2='TT' WHERE lg_iso_2='TT';
UPDATE static_languages SET lg_name_ko='텔루구어',lg_iso_2='TE' WHERE lg_iso_2='TE';
UPDATE static_languages SET lg_name_ko='태국어',lg_iso_2='TH' WHERE lg_iso_2='TH';
UPDATE static_languages SET lg_name_ko='티베트어',lg_iso_2='BO' WHERE lg_iso_2='BO';
UPDATE static_languages SET lg_name_ko='티그리냐어',lg_iso_2='TI' WHERE lg_iso_2='TI';
UPDATE static_languages SET lg_name_ko='통가어',lg_iso_2='TO' WHERE lg_iso_2='TO';
UPDATE static_languages SET lg_name_ko='총가어',lg_iso_2='TS' WHERE lg_iso_2='TS';
UPDATE static_languages SET lg_name_ko='터키어',lg_iso_2='TR' WHERE lg_iso_2='TR';
UPDATE static_languages SET lg_name_ko='투르크멘어',lg_iso_2='TK' WHERE lg_iso_2='TK';
UPDATE static_languages SET lg_name_ko='트위어',lg_iso_2='TW' WHERE lg_iso_2='TW';
UPDATE static_languages SET lg_name_ko='위구르어',lg_iso_2='UG' WHERE lg_iso_2='UG';
UPDATE static_languages SET lg_name_ko='우크라이나어',lg_iso_2='UK' WHERE lg_iso_2='UK';
UPDATE static_languages SET lg_name_ko='우르두어',lg_iso_2='UR' WHERE lg_iso_2='UR';
UPDATE static_languages SET lg_name_ko='우즈베크어',lg_iso_2='UZ' WHERE lg_iso_2='UZ';
UPDATE static_languages SET lg_name_ko='베트남어',lg_iso_2='VI' WHERE lg_iso_2='VI';
UPDATE static_languages SET lg_name_ko='볼라퓌크어',lg_iso_2='VO' WHERE lg_iso_2='VO';
UPDATE static_languages SET lg_name_ko='웨일스어',lg_iso_2='CY' WHERE lg_iso_2='CY';
UPDATE static_languages SET lg_name_ko='올로프어',lg_iso_2='WO' WHERE lg_iso_2='WO';
UPDATE static_languages SET lg_name_ko='코사어',lg_iso_2='XH' WHERE lg_iso_2='XH';
UPDATE static_languages SET lg_name_ko='이디시어',lg_iso_2='YI' WHERE lg_iso_2='YI';
UPDATE static_languages SET lg_name_ko='요루바어',lg_iso_2='YO' WHERE lg_iso_2='YO';
UPDATE static_languages SET lg_name_ko='줄루어',lg_iso_2='ZU' WHERE lg_iso_2='ZU';
UPDATE static_languages SET lg_name_ko='보스니아어',lg_iso_2='BS' WHERE lg_iso_2='BS';
UPDATE static_languages SET lg_name_ko='아베스타어',lg_iso_2='AE' WHERE lg_iso_2='AE';
UPDATE static_languages SET lg_name_ko='아칸어',lg_iso_2='AK' WHERE lg_iso_2='AK';
UPDATE static_languages SET lg_name_ko='아라곤어',lg_iso_2='AN' WHERE lg_iso_2='AN';
UPDATE static_languages SET lg_name_ko='아바릭어',lg_iso_2='AV' WHERE lg_iso_2='AV';
UPDATE static_languages SET lg_name_ko='밤바라어',lg_iso_2='BM' WHERE lg_iso_2='BM';
UPDATE static_languages SET lg_name_ko='체첸어',lg_iso_2='CE' WHERE lg_iso_2='CE';
UPDATE static_languages SET lg_name_ko='차모로어',lg_iso_2='CH' WHERE lg_iso_2='CH';
UPDATE static_languages SET lg_name_ko='크리어',lg_iso_2='CR' WHERE lg_iso_2='CR';
UPDATE static_languages SET lg_name_ko='교회 슬라브어',lg_iso_2='CU' WHERE lg_iso_2='CU';
UPDATE static_languages SET lg_name_ko='추바시어',lg_iso_2='CV' WHERE lg_iso_2='CV';
UPDATE static_languages SET lg_name_ko='디베히어',lg_iso_2='DV' WHERE lg_iso_2='DV';
UPDATE static_languages SET lg_name_ko='에웨어',lg_iso_2='EE' WHERE lg_iso_2='EE';
UPDATE static_languages SET lg_name_ko='풀라어',lg_iso_2='FF' WHERE lg_iso_2='FF';
UPDATE static_languages SET lg_name_ko='히리 모투어',lg_iso_2='HO' WHERE lg_iso_2='HO';
UPDATE static_languages SET lg_name_ko='아이티어',lg_iso_2='HT' WHERE lg_iso_2='HT';
UPDATE static_languages SET lg_name_ko='헤레로어',lg_iso_2='HZ' WHERE lg_iso_2='HZ';
UPDATE static_languages SET lg_name_ko='이그보어',lg_iso_2='IG' WHERE lg_iso_2='IG';
UPDATE static_languages SET lg_name_ko='쓰촨 이어',lg_iso_2='II' WHERE lg_iso_2='II';
UPDATE static_languages SET lg_name_ko='이도어',lg_iso_2='IO' WHERE lg_iso_2='IO';
UPDATE static_languages SET lg_name_ko='자바어',lg_iso_2='JV' WHERE lg_iso_2='JV';
UPDATE static_languages SET lg_name_ko='콩고어',lg_iso_2='KG' WHERE lg_iso_2='KG';
UPDATE static_languages SET lg_name_ko='키쿠유어',lg_iso_2='KI' WHERE lg_iso_2='KI';
UPDATE static_languages SET lg_name_ko='쿠안야마어',lg_iso_2='KJ' WHERE lg_iso_2='KJ';
UPDATE static_languages SET lg_name_ko='칸누리어',lg_iso_2='KR' WHERE lg_iso_2='KR';
UPDATE static_languages SET lg_name_ko='코미어',lg_iso_2='KV' WHERE lg_iso_2='KV';
UPDATE static_languages SET lg_name_ko='콘월어',lg_iso_2='KW' WHERE lg_iso_2='KW';
UPDATE static_languages SET lg_name_ko='룩셈부르크어',lg_iso_2='LB' WHERE lg_iso_2='LB';
UPDATE static_languages SET lg_name_ko='간다어',lg_iso_2='LG' WHERE lg_iso_2='LG';
UPDATE static_languages SET lg_name_ko='림버거어',lg_iso_2='LI' WHERE lg_iso_2='LI';
UPDATE static_languages SET lg_name_ko='루바-카탄가어',lg_iso_2='LU' WHERE lg_iso_2='LU';
UPDATE static_languages SET lg_name_ko='마셜제도어',lg_iso_2='MH' WHERE lg_iso_2='MH';
UPDATE static_languages SET lg_name_ko='노르웨이어(보크말)',lg_iso_2='NB' WHERE lg_iso_2='NB';
UPDATE static_languages SET lg_name_ko='북부 은데벨레어',lg_iso_2='ND' WHERE lg_iso_2='ND';
UPDATE static_languages SET lg_name_ko='느동가어',lg_iso_2='NG' WHERE lg_iso_2='NG';
UPDATE static_languages SET lg_name_ko='노르웨이어(니노르스크)',lg_iso_2='NN' WHERE lg_iso_2='NN';
UPDATE static_languages SET lg_name_ko='남부 은데벨레어',lg_iso_2='NR' WHERE lg_iso_2='NR';
UPDATE static_languages SET lg_name_ko='나바호어',lg_iso_2='NV' WHERE lg_iso_2='NV';
UPDATE static_languages SET lg_name_ko='니안자어; 치츄어; 츄어',lg_iso_2='NY' WHERE lg_iso_2='NY';
UPDATE static_languages SET lg_name_ko='오지브웨이어',lg_iso_2='OJ' WHERE lg_iso_2='OJ';
UPDATE static_languages SET lg_name_ko='오세트어',lg_iso_2='OS' WHERE lg_iso_2='OS';
UPDATE static_languages SET lg_name_ko='팔리어',lg_iso_2='PI' WHERE lg_iso_2='PI';
UPDATE static_languages SET lg_name_ko='사르디니아어',lg_iso_2='SC' WHERE lg_iso_2='SC';
UPDATE static_languages SET lg_name_ko='북부 사미어',lg_iso_2='SE' WHERE lg_iso_2='SE';
UPDATE static_languages SET lg_name_ko='타히티어',lg_iso_2='TY' WHERE lg_iso_2='TY';
UPDATE static_languages SET lg_name_ko='벤다어',lg_iso_2='VE' WHERE lg_iso_2='VE';
UPDATE static_languages SET lg_name_ko='왈론어',lg_iso_2='WA' WHERE lg_iso_2='WA';
UPDATE static_languages SET lg_name_ko='포르투갈어',lg_iso_2='PT' WHERE lg_iso_2='PT';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='프랑스어',lg_iso_2='FR' WHERE lg_iso_2='FR';
UPDATE static_languages SET lg_name_ko='타갈로그어',lg_iso_2='TL' WHERE lg_iso_2='TL';
UPDATE static_languages SET lg_name_ko='세르비아-크로아티아어',lg_iso_2='SH' WHERE lg_iso_2='SH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ko='중국어',lg_iso_2='ZH' WHERE lg_iso_2='ZH';


